### ISSUE TITLE
Bug when assigning `oci_core_cross_connect` to a `oci_core_cross_connect_group`

### ISSUE THREAD

**Issue by brodster2** [oci-landing-zones/terraform-oci-modules-networking#37]
Hello 👋
We are using the [oracle oci-landing-zones/terraform-oci-modules-orchestrator](https://github.com/oci-landing-zones/terraform-oci-modules-orchestrator/tree/main) to setup our OCI LZ. We've run into a problem when trying to create cross connects as part of cross connect groups, an example of our configuration:
```json
...
"cross_connect_groups": {
  "FC-UK3-Equinix-LD6": {
    "compartment_id": "CMP-LZP-NETWORK-KEY",
    "cross_connects": {
      "FC-UK3-Equinix-LD6-1": {
        "compartment_id": "CMP-LZP-NETWORK-KEY",
        "location_name": "Equinix LD6",
        "port_speed_shape_name": "10 Gbps"
      }
    }
  }
}
...
```

This gets sent to the networking module https://github.com/oci-landing-zones/terraform-oci-modules-orchestrator/blob/17f621d5efb08577cd105859fbf05d4cdeac9376/networking.tf#L8

We have no problem when creating just the cross connect groups, the issue comes when the `oci_core_cross_connect` is created and assigned to a `oci_core_cross_connect_group` [here](https://github.com/oci-landing-zones/terraform-oci-modules-networking/blob/aaf1f1ca4ae01a669409c9b6d4f16371f2422cbb/cross-connects.tf#L54) which results in the error:
```
│ Error: Invalid index
│ 
│   on .terraform/modules/oci_lz_network/cross-connects.tf line 54, in resource "oci_core_cross_connect" "these":
│   54:   cross_connect_group_id                       = oci_core_cross_connect_group.these[each.key].id
│     ├────────────────
│     │ each.key is "FC-UK3-Equinix-LD6-1"
│     │ oci_core_cross_connect_group.these is object with 1 attributes
```

Which makes sense, because the cross connect group attribute will be `oci_core_cross_connect_group.these[FC-UK3-Equinix-LD6]` but the code on line 54 of cross-connects.tf is looking for `oci_core_cross_connect_group.these[FC-UK3-Equinix-LD6-1]` which doesn't exist because that is the unique key of the cross connect. I think line 54 needs to be updated from:
```terraform
cross_connect_group_id                       = oci_core_cross_connect_group.these[each.key].id
```
to:
```terraform
cross_connect_group_id                       = oci_core_cross_connect_group.these[each.value.cross_connect_group_id].id
```

**Comment by andrecorreaneto** [comment]
Hello brodster2, thanks for reporting. I agree there's a bug and we'll have this fixed in the next release.

**Comment by andrecorreaneto** [comment]
Hi brodster2, can you please test https://github.com/oci-landing-zones/terraform-oci-modules-orchestrator/tree/release-2.0.4? It has the fix. In a few day we'll be merging this release candidate into main.

**Comment by andrecorreaneto** [comment]
Fix available in v0.6.9.

**Comment by brodster2** [comment]
> Hi brodster2, can you please test https://github.com/oci-landing-zones/terraform-oci-modules-orchestrator/tree/release-2.0.4? It has the fix. In a few days we'll be merging this candidate release into main.

Hi @andrecorreaneto, thanks for the quick response, we attempted to test that branch but ran across this error:
```
│ Error: Experiment has concluded
│ 
│   on providers.tf line 58, in terraform:
│   58:   experiments = [module_variable_optional_attrs]
│ 
│ Experiment "module_variable_optional_attrs" is no longer available. The
│ final feature corresponding to this experiment differs from the
│ experimental form and is available in the Terraform language from Terraform
│ v1.3.0 onwards.
```

since that branch requires [terraform versions >=1.3.0](https://github.com/oci-landing-zones/terraform-oci-modules-orchestrator/blob/7f8d9b04de2776384a413b94d5b15ccd5f34c066/providers.tf#L50) but still has the `module_variable_optional_attrs` experiment set. We tried with Terraform versions 1.3.x and 1.5.x

**Comment by brodster2** [comment]
https://github.com/hashicorp/terraform/issues/31931 has some details on it

**Comment by andrecorreaneto** [comment]
Please retry, just pushed the fix. Sorry about that.

**Comment by brodster2** [comment]
Hi @andrecorreaneto, we had to create the cross connects manually to get the LOAs to our provider. But using the branch https://github.com/oci-landing-zones/terraform-oci-modules-orchestrator/tree/release-2.0.4 we had no issues importing them into state with no changes shown. So I'm happy to call this issue closed. Thanks for your quick fix.
