### ISSUE TITLE
Service Gateways Only Provide Access to Object Storage

### ISSUE THREAD

**Issue by Kamil-Stachura** [oci-landing-zones/terraform-oci-modules-networking#7]
Hi Team,

When defining the network configuration, there is no option to select the type of service provided by the service gateways. Based on the [service_gateways.tf ](https://github.com/oracle-quickstart/terraform-oci-cis-landing-zone-networking/blob/main/service_gateways.tf), this defaults to "objectstorage".

As a result, when provisioning OKE node pools, these cannot be setup as they require access to all OCI services to complete the provisioning.

To test, I have manually altered the service gateway to provide all services, which resulted in successfully provisioned OKE node pools.

Please consider implementing the option to choose the service type (all/object storage).

Thank you in advance!

**Comment by andrecorreaneto** [comment]
This has been solved.

Use either
`destination        = "objectostorage"`
or 
`destination        = "all-services"`

Thanks.
